local fs = require("@std/fs")
local path = require("@std/path")
local test = require("@std/test")
local asserts = require("@std/test/assert")
local parser = require("@std/syntax/parser")
local printer = require("@std/syntax/printer")
local syntax = require("@std/syntax")
local T = require("@std/luau")

local function assertEqualsLocation(
	assert: asserts.Asserts,
	actual: T.Location,
	startLine: number,
	startColumn: number,
	endLine: number,
	endColumn: number
)
	assert.eq(actual.begin.line, startLine)
	assert.eq(actual.begin.column, startColumn)
	assert.eq(actual["end"].line, endLine)
	assert.eq(actual["end"].column, endColumn)
end

test.suite("Parser", function(suite)
	suite:case("tokenContainsLeadingSpaces", function(assert)
		local block = parser.parseblock("  local x = 1")
		assert.eq(#block.statements, 1)

		local l = block.statements[1]
		assert.eq(l.tag, "local")

		local token = (l :: syntax.AstStatLocal).localkeyword
		assert.eq(#token.leadingtrivia, 1)
		assert.eq(token.leadingtrivia[1].tag, "whitespace")
		assert.eq(token.leadingtrivia[1].text, "  ")
		assertEqualsLocation(assert, token.leadingtrivia[1].location, 0, 0, 0, 2)
	end)

	suite:case("tokenContainsLeadingNewline", function(assert)
		local block = parser.parseblock("\n" .. "local x = 1")
		assert.eq(#block.statements, 1)

		local l = block.statements[1]
		assert.eq(l.tag, "local")

		local token = (l :: syntax.AstStatLocal).localkeyword
		assert.eq(#token.leadingtrivia, 1)
		assert.eq(token.leadingtrivia[1].tag, "whitespace")
		assert.eq(token.leadingtrivia[1].text, "\n")
		assertEqualsLocation(assert, token.leadingtrivia[1].location, 0, 0, 1, 0)
	end)

	suite:case("tokenContainsLeadingSingleLineComment", function(assert)
		local block = parser.parseblock("-- comment\n" .. "local x = 1")
		assert.eq(#block.statements, 1)

		local l = block.statements[1]
		assert.eq(l.tag, "local")

		local token = (l :: syntax.AstStatLocal).localkeyword
		assert.eq(#token.leadingtrivia, 2)
		assert.eq(token.leadingtrivia[1].tag, "comment")
		assert.eq(token.leadingtrivia[1].text, "-- comment")
		assertEqualsLocation(assert, token.leadingtrivia[1].location, 0, 0, 0, 10)
		assert.eq(token.leadingtrivia[2].tag, "whitespace")
		assert.eq(token.leadingtrivia[2].text, "\n")
		assertEqualsLocation(assert, token.leadingtrivia[2].location, 0, 10, 1, 0)
	end)

	suite:case("tokenContainsLeadingBlockComment", function(assert)
		local block = parser.parseblock("--[[ comment ]] local x = 1")
		assert.eq(#block.statements, 1)

		local l = block.statements[1]
		assert.eq(l.tag, "local")

		local token = (l :: syntax.AstStatLocal).localkeyword
		assert.eq(#token.leadingtrivia, 2)
		assert.eq(token.leadingtrivia[1].tag, "blockcomment")
		assert.eq(token.leadingtrivia[1].text, "--[[ comment ]]")
		assertEqualsLocation(assert, token.leadingtrivia[1].location, 0, 0, 0, 15)
		assert.eq(token.leadingtrivia[2].tag, "whitespace")
		assert.eq(token.leadingtrivia[2].text, " ")
		assertEqualsLocation(assert, token.leadingtrivia[2].location, 0, 15, 0, 16)
	end)

	suite:case("tokenizeWhitespace", function(assert)
		local block = parser.parseblock("  \n\t\t\n\n" .. "local x = 1")
		assert.eq(#block.statements, 1)

		local l = block.statements[1]
		assert.eq(l.tag, "local")

		local token = (l :: syntax.AstStatLocal).localkeyword
		assert.eq(#token.leadingtrivia, 3)
		assert.eq(token.leadingtrivia[1].text, "  \n")
		assert.eq(token.leadingtrivia[2].text, "\t\t\n")
		assert.eq(token.leadingtrivia[3].text, "\n")
	end)

	suite:case("triviaSplitBetweenLeadingAndTrailing", function(assert)
		local block = parser.parseblock("local x = 'test' -- comment\n" .. "-- comment 2\nlocal y = 'value'")
		assert.eq(#block.statements, 2)

		local firstStmt = block.statements[1]
		assert.eq(firstStmt.tag, "local")

		local trailingToken: syntax.AstExpr = (firstStmt :: syntax.AstStatLocal).values[1].node
		assert.eq(trailingToken.tag, "string")
		local expr = trailingToken :: syntax.AstExprConstantString
		assert.eq(#expr.trailingtrivia, 3)
		assert.eq(expr.trailingtrivia[1].text, " ")
		assert.eq(expr.trailingtrivia[2].text, "-- comment")
		assert.eq(expr.trailingtrivia[3].text, "\n")

		local secondStmt = block.statements[2]
		assert.eq(secondStmt.tag, "local")

		local leadingToken = (secondStmt :: syntax.AstStatLocal).localkeyword
		assert.eq(#leadingToken.leadingtrivia, 2)
		assert.eq(leadingToken.leadingtrivia[1].text, "-- comment 2")
		assert.eq(leadingToken.leadingtrivia[2].text, "\n")
	end)

	suite:case("roundtrippableAst", function(assert)
		local function visitDirectory(directory: string)
			for _, entry in fs.listdir(directory) do
				if entry.type ~= "file" then
					continue
				end
				local p = path.join(directory, entry.name)
				local source = fs.readfiletostring(path.format(p))
				local result = printer.printfile(parser.parse(source))

				assert.eq(source, result)
			end
		end

		visitDirectory("examples")
		visitDirectory("tests/parserExamples")
	end)

	suite:case("lineOffsetsField", function(assert)
		local singleLineCode = "local x = 1"
		local result = parser.parse(singleLineCode)

		assert.eq(type(result.lineoffsets), "table")
		assert.eq(#result.lineoffsets, 1)
		assert.eq(result.lineoffsets[1], 0)

		local multiLineCode = "local x = 1\nlocal y = 2\nlocal z = 3"
		local multiResult = parser.parse(multiLineCode)

		assert.eq(type(multiResult.lineoffsets), "table")
		assert.eq(#multiResult.lineoffsets, 3)
		assert.eq(multiResult.lineoffsets[1], 0)
		assert.eq(multiResult.lineoffsets[2], 12)
		assert.eq(multiResult.lineoffsets[3], 24)

		local emptyLineCode = "local x = 1\n\nlocal y = 2"
		local emptyResult = parser.parse(emptyLineCode)

		assert.eq(type(emptyResult.lineoffsets), "table")
		assert.eq(#emptyResult.lineoffsets, 3)
		assert.eq(emptyResult.lineoffsets[1], 0)
		assert.eq(emptyResult.lineoffsets[2], 12)
		assert.eq(emptyResult.lineoffsets[3], 13)
	end)

	suite:case("canParseAttributes", function(assert)
		local code = [[
			@checked
			local function foo()
			end
		]]
		local subcases = {
			{ attr = "@checked", code = code },
			{ attr = "@native", code = code:gsub("checked", "native") },
			{ attr = "@deprecated", code = code:gsub("checked", "deprecated") },
		}

		for _, subcase in ipairs(subcases) do
			local block = parser.parseblock(subcase.code)
			assert.eq(#block.statements, 1)

			local l = block.statements[1]
			assert.eq(l.tag, "localfunction")

			local lf = l :: syntax.AstStatLocalFunction
			assert.eq(lf.attributes[1].text, subcase.attr)
		end
	end)
end)

test.suite("parseExpr", function(suite)
	suite:case("parseExprGroup", function(assert)
		local groupExpr = parser.parseexpr("(x)")
		assert.eq(groupExpr.tag, "group")
		assert.eq(groupExpr.kind, "expr")
		local expr = groupExpr :: syntax.AstExprGroup
		assert.eq(expr.openparens.text, "(")
		assert.eq(expr.closeparens.text, ")")
		assert.eq(expr.expression.tag, "global")
	end)

	suite:case("parseExprNil", function(assert)
		local expr = parser.parseexpr("nil")
		assert.eq(expr.tag, "nil")
		assert.eq(expr.kind, "expr")
		assert.eq((expr :: syntax.AstExprConstantNil).text, "nil")
	end)

	suite:case("parseExprBoolean", function(assert)
		local trueExpr = parser.parseexpr("true")
		assert.eq(trueExpr.tag, "boolean")
		assert.eq(trueExpr.kind, "expr")
		assert.eq((trueExpr :: syntax.AstExprConstantBool).text, "true")
		assert.eq((trueExpr :: syntax.AstExprConstantBool).value, true)

		local falseExpr = parser.parseexpr("false")
		assert.eq(falseExpr.tag, "boolean")
		assert.eq(falseExpr.kind, "expr")
		assert.eq((falseExpr :: syntax.AstExprConstantBool).text, "false")
		assert.eq((falseExpr :: syntax.AstExprConstantBool).value, false)
	end)

	suite:case("parseExprNumber", function(assert)
		local numberExpr = parser.parseexpr("42")
		assert.eq(numberExpr.tag, "number")
		assert.eq(numberExpr.kind, "expr")
		assert.eq((numberExpr :: syntax.AstExprConstantNumber).text, "42")
		assert.eq((numberExpr :: syntax.AstExprConstantNumber).value, 42)

		local floatExpr = parser.parseexpr("3.14")
		assert.eq(floatExpr.tag, "number")
		assert.eq(floatExpr.kind, "expr")
		assert.eq((floatExpr :: syntax.AstExprConstantNumber).text, "3.14")
		assert.eq((floatExpr :: syntax.AstExprConstantNumber).value, 3.14)
	end)

	suite:case("parseExprString", function(assert)
		local singleQuoteExpr = parser.parseexpr("'hello'")
		assert.eq(singleQuoteExpr.tag, "string")
		assert.eq(singleQuoteExpr.kind, "expr")
		assert.eq((singleQuoteExpr :: syntax.AstExprConstantString).text, "hello")
		assert.eq((singleQuoteExpr :: syntax.AstExprConstantString).quotestyle, "single")

		local doubleQuoteExpr = parser.parseexpr('"world"')
		assert.eq(doubleQuoteExpr.tag, "string")
		assert.eq(doubleQuoteExpr.kind, "expr")
		assert.eq((doubleQuoteExpr :: syntax.AstExprConstantString).text, "world")
		assert.eq((doubleQuoteExpr :: syntax.AstExprConstantString).quotestyle, "double")

		local blockQuoteExpr = parser.parseexpr("[[world]]")
		assert.eq(blockQuoteExpr.tag, "string")
		assert.eq(blockQuoteExpr.kind, "expr")
		assert.eq((blockQuoteExpr :: syntax.AstExprConstantString).text, "world")
		assert.eq((blockQuoteExpr :: syntax.AstExprConstantString).quotestyle, "block")

		local interpExpr = parser.parseexpr("`foobar`")
		assert.eq(interpExpr.tag, "string")
		assert.eq(interpExpr.kind, "expr")
		assert.eq((interpExpr :: syntax.AstExprConstantString).text, "foobar")
		assert.eq((interpExpr :: syntax.AstExprConstantString).quotestyle, "interp")
	end)

	suite:case("parseExprLocal", function(assert)
		local localExpr = parser.parseexpr("x")
		assert.eq(localExpr.tag, "global")
		assert.eq(localExpr.kind, "expr")
		assert.eq((localExpr :: syntax.AstExprGlobal).name.text, "x")
	end)

	suite:case("parseExprGlobal", function(assert)
		local globalExpr = parser.parseexpr("_G")
		assert.eq(globalExpr.tag, "global")
		assert.eq(globalExpr.kind, "expr")
		assert.eq((globalExpr :: syntax.AstExprGlobal).name.text, "_G")
	end)

	suite:case("parseExprVarargs", function(assert)
		local varargsExpr = parser.parseexpr("...")
		assert.eq(varargsExpr.tag, "vararg")
		assert.eq(varargsExpr.kind, "expr")
		assert.eq((varargsExpr :: syntax.AstExprVarargs).text, "...")
	end)

	suite:case("parseExprCall", function(assert)
		local callExpr = parser.parseexpr("foo()")
		assert.eq(callExpr.tag, "call")
		assert.eq(callExpr.kind, "expr")
		assert.eq((callExpr :: syntax.AstExprCall).func.tag, "global")
		assert.eq(((callExpr :: syntax.AstExprCall).func :: syntax.AstExprGlobal).name.text, "foo")
		assert.eq((callExpr :: syntax.AstExprCall).self, false)
		assert.eq(#(callExpr :: syntax.AstExprCall).arguments, 0)

		local callWithArgsExpr = parser.parseexpr("bar(1, 2)")
		assert.eq(callWithArgsExpr.tag, "call")
		assert.eq(callWithArgsExpr.kind, "expr")
		assert.eq(#(callWithArgsExpr :: syntax.AstExprCall).arguments, 2)
		assert.eq((callWithArgsExpr :: syntax.AstExprCall).arguments[1].node.tag, "number")
		assert.eq((callWithArgsExpr :: syntax.AstExprCall).arguments[2].node.tag, "number")
	end)

	suite:case("parseExprIndexName", function(assert)
		local indexExpr = parser.parseexpr("obj.field")
		assert.eq(indexExpr.tag, "indexname")
		assert.eq(indexExpr.kind, "expr")
		assert.eq((indexExpr :: syntax.AstExprIndexName).expression.tag, "global")
		assert.eq((indexExpr :: syntax.AstExprIndexName).accessor.text, ".")
		assert.eq((indexExpr :: syntax.AstExprIndexName).index.text, "field")
	end)

	suite:case("parseExprIndexExpr", function(assert)
		local indexExpr = parser.parseexpr("arr[1]")
		assert.eq(indexExpr.tag, "index")
		assert.eq(indexExpr.kind, "expr")
		assert.eq((indexExpr :: syntax.AstExprIndexExpr).expression.tag, "global")
		assert.eq((indexExpr :: syntax.AstExprIndexExpr).index.tag, "number")
		assert.eq((indexExpr :: syntax.AstExprIndexExpr).openbrackets.text, "[")
		assert.eq((indexExpr :: syntax.AstExprIndexExpr).closebrackets.text, "]")
	end)

	suite:case("parseExprAnonymousFunction", function(assert)
		local anonFuncExpr = parser.parseexpr("function(a, b) return a + b end")
		assert.eq(anonFuncExpr.tag, "function")
		assert.eq(anonFuncExpr.kind, "expr")

		local funcExpr = anonFuncExpr :: syntax.AstExprAnonymousFunction
		assert.eq(#funcExpr.attributes, 0)
		assert.eq(funcExpr.functionkeyword.text, "function")

		local funcBody = funcExpr.body
		assert.eq(funcBody.opengenerics, nil)
		assert.eq(funcBody.generics, nil)
		assert.eq(funcBody.genericpacks, nil)
		assert.eq(funcBody.closegenerics, nil)
		assert.eq(funcBody.self, nil)
		assert.eq(funcBody.openparens.text, "(")
		assert.eq(#funcBody.parameters, 2)
		assert.eq(funcBody.parameters[1].node.name.text, "a")
		assert.eq(funcBody.parameters[2].node.name.text, "b")
		assert.eq(funcBody.vararg, nil)
		assert.eq(funcBody.varargcolon, nil)
		assert.eq(funcBody.varargannotation, nil)
		assert.eq(funcBody.closeparens.text, ")")
		assert.eq(funcBody.returnspecifier, nil)
		assert.eq(funcBody.returnannotation, nil)
		assert.eq(funcBody.endkeyword.text, "end")

		anonFuncExpr = parser.parseexpr("function<A, B...>(a: A, ...: B...): A return a end")
		assert.eq(anonFuncExpr.tag, "function")
		assert.eq(anonFuncExpr.kind, "expr")

		funcExpr = anonFuncExpr :: syntax.AstExprAnonymousFunction
		assert.eq(#funcExpr.attributes, 0)
		assert.eq(funcExpr.functionkeyword.text, "function")

		funcBody = funcExpr.body
		assert.neq(funcBody.opengenerics, nil)
		assert.neq(funcBody.generics, nil)

		assert.eq(#funcBody.generics :: syntax.Punctuated<syntax.AstGenericType>, 1)
		local gen = (funcBody.generics :: syntax.Punctuated<syntax.AstGenericType>)[1].node
		assert.eq(gen.name.text, "A")
		assert.eq(gen.equals, nil)
		assert.eq(gen.default, nil)

		assert.neq(funcBody.genericpacks, nil)
		assert.eq(#funcBody.genericpacks :: syntax.Punctuated<syntax.AstGenericTypePack>, 1)
		local genPack = (funcBody.genericpacks :: syntax.Punctuated<syntax.AstGenericTypePack>)[1].node
		assert.eq(genPack.name.text, "B")
		assert.eq(genPack.ellipsis.text, "...")
		assert.eq(genPack.equals, nil)
		assert.eq(genPack.default, nil)

		assert.neq(funcBody.closegenerics, nil)
		assert.eq((funcBody.closegenerics :: syntax.Token<">">).text, ">")

		assert.eq(funcBody.openparens.text, "(")
		assert.eq(#funcBody.parameters, 1)

		local param = funcBody.parameters[1].node
		assert.eq(param.name.text, "a")
		assert.neq(param.colon, nil)
		assert.eq((param.colon :: syntax.Token<":">).text, ":")
		assert.neq(param.annotation, nil)
		assert.eq((param.annotation :: syntax.AstType).tag, "reference")

		assert.neq(funcBody.vararg, nil)
		assert.eq((funcBody.vararg :: syntax.Token<"...">).text, "...")
		assert.neq(funcBody.varargcolon, nil)
		assert.eq((funcBody.varargcolon :: syntax.Token<":">).text, ":")
		assert.neq(funcBody.varargannotation, nil)
		assert.eq((funcBody.varargannotation :: syntax.AstTypePack).tag, "generic")

		assert.eq(funcBody.closeparens.text, ")")
		assert.neq(funcBody.returnspecifier, nil)
		assert.eq((funcBody.returnspecifier :: syntax.Token<":">).text, ":")
		assert.neq(funcBody.returnannotation, nil)
		assert.eq((funcBody.returnannotation :: syntax.AstTypePack).tag, "explicit")
	end)

	suite:case("parseExprTable", function(assert)
		local emptyTableExpr = parser.parseexpr("{}")
		assert.eq(emptyTableExpr.tag, "table")
		assert.eq(emptyTableExpr.kind, "expr")
		local tableExpr = emptyTableExpr :: syntax.AstExprTable
		assert.eq(tableExpr.openbrace.text, "{")
		assert.eq(tableExpr.closebrace.text, "}")
		assert.eq(#tableExpr.entries, 0)

		local mixedTable = parser.parseexpr("{1, foo = bar; [2] = baz}")
		assert.eq(mixedTable.tag, "table")
		assert.eq(mixedTable.kind, "expr")
		local mixedTableExpr = mixedTable :: syntax.AstExprTable
		assert.eq(#mixedTableExpr.entries, 3)

		local entry1 = mixedTableExpr.entries[1]
		assert.eq(entry1.kind, "list")
		assert.eq(entry1.value.tag, "number")
		assert.neq(entry1.separator, nil)
		assert.eq((entry1.separator :: syntax.Token<"," | ";">).text, ",")

		local entry2: any = mixedTableExpr.entries[2]
		assert.eq(entry2.kind, "record")
		assert.eq(entry2.key.text, "foo")
		assert.eq(entry2.equals.text, "=")
		assert.eq(entry2.value.tag, "global")
		assert.neq(entry2.separator, nil)
		assert.eq((entry2.separator :: syntax.Token<"," | ";">).text, ";")

		local entry3: any = mixedTableExpr.entries[3]
		assert.eq(entry3.kind, "general")
		assert.eq(entry3.indexeropen.text, "[")
		assert.eq(entry3.key.tag, "number")
		assert.eq(entry3.indexerclose.text, "]")
		assert.eq(entry3.equals.text, "=")
		assert.eq(entry3.value.tag, "global")
		assert.eq(entry3.separator, nil)
	end)

	suite:case("parseExprUnary", function(assert)
		local notExpr = parser.parseexpr("not x")
		assert.eq(notExpr.tag, "unary")
		assert.eq(notExpr.kind, "expr")
		local expr = notExpr :: syntax.AstExprUnary
		assert.eq(expr.operator.text, "not")
		assert.eq(expr.operand.tag, "global")

		local negExpr = parser.parseexpr("-42")
		assert.eq(negExpr.tag, "unary")
		assert.eq(negExpr.kind, "expr")
		expr = negExpr :: syntax.AstExprUnary
		assert.eq(expr.operator.text, "-")
		assert.eq(expr.operand.tag, "number")

		local lenExpr = parser.parseexpr("#str")
		assert.eq(lenExpr.tag, "unary")
		assert.eq(lenExpr.kind, "expr")
		expr = lenExpr :: syntax.AstExprUnary
		assert.eq(expr.operator.text, "#")
		assert.eq(expr.operand.tag, "global")
	end)

	suite:case("parseExprBinary", function(assert)
		local addExpr = parser.parseexpr("1 + 2")
		assert.eq(addExpr.tag, "binary")
		assert.eq(addExpr.kind, "expr")
		local expr = addExpr :: syntax.AstExprBinary
		assert.eq(expr.lhsoperand.tag, "number")
		assert.eq(expr.operator.text, "+")
		assert.eq(expr.rhsoperand.tag, "number")
	end)

	suite:case("parseExprInterpString", function(assert)
		local interpExpr = parser.parseexpr("`Hello, {name}! Today is {dayOfWeek}.`")
		assert.eq(interpExpr.tag, "interpolatedstring")
		assert.eq(interpExpr.kind, "expr")
		local expr = interpExpr :: syntax.AstExprInterpString
		assert.eq(#expr.strings, 3)

		assert.eq(expr.strings[1].text, "Hello, ")
		assert.eq(expr.strings[2].text, "! Today is ")
		assert.eq(expr.strings[3].text, ".")

		assert.eq(#expr.expressions, 2)
		assert.eq(expr.expressions[1].tag, "global")
		assert.eq(expr.expressions[2].tag, "global")
	end)

	suite:case("parseExprTypeAssertion", function(assert)
		local castExpr = parser.parseexpr("x :: string")
		assert.eq(castExpr.tag, "cast")
		assert.eq(castExpr.kind, "expr")
		local expr = castExpr :: syntax.AstExprTypeAssertion
		assert.eq(expr.operand.tag, "global")
		assert.eq(expr.operator.text, "::")
		assert.eq(expr.annotation.tag, "reference")
	end)
end)

local function checkIsBlock(node: any, assert: asserts.Asserts)
	assert.eq(node.kind, "stat")
	assert.eq(node.tag, "block")
end

test.suite("parse", function(suite)
	suite:case("parseEmptyProgram", function(assert)
		local block = parser.parseblock("")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 0)
	end)

	suite:case("parseIfStatement", function(assert)
		local block = parser.parseblock(
			"if x > 0 then print('positive') elseif x < 0 then print('negative') else print('zero') end"
		)
		assert.eq(#block.statements, 1)

		local ifStat = block.statements[1] :: syntax.AstStatIf
		assert.eq(ifStat.tag, "conditional")
		assert.eq(ifStat.ifkeyword.text, "if")
		assert.eq(ifStat.condition.tag, "binary")
		assert.eq(ifStat.thenkeyword.text, "then")
		checkIsBlock(ifStat.thenblock, assert)

		local thenBlock = ifStat.thenblock
		assert.eq(#thenBlock.statements, 1)

		assert.eq(#ifStat.elseifs, 1)
		local elseIf = ifStat.elseifs[1]
		assert.eq(elseIf.elseifkeyword.text, "elseif")
		assert.eq(elseIf.condition.tag, "binary")
		assert.eq(elseIf.thenkeyword.text, "then")
		checkIsBlock(elseIf.thenblock, assert)

		assert.neq(ifStat.elsekeyword, nil)
		assert.eq((ifStat.elsekeyword :: syntax.Token<"else">).text, "else")
		assert.neq(ifStat.elseblock, nil)
		checkIsBlock(ifStat.elseblock, assert)
		assert.eq(ifStat.endkeyword.text, "end")

		block = parser.parseblock("if condition then doSomething() end")
		assert.eq(#block.statements, 1)
		local simpleIfStat = block.statements[1] :: syntax.AstStatIf
		assert.eq(simpleIfStat.tag, "conditional")
		assert.eq(simpleIfStat.ifkeyword.text, "if")
		assert.eq(simpleIfStat.condition.tag, "global")
		assert.eq(simpleIfStat.thenkeyword.text, "then")
		checkIsBlock(simpleIfStat.thenblock, assert)
		assert.eq(#simpleIfStat.thenblock.statements, 1)
		assert.eq(#simpleIfStat.elseifs, 0)
		assert.eq(simpleIfStat.elsekeyword, nil)
		assert.eq(simpleIfStat.elseblock, nil)
		assert.eq(simpleIfStat.endkeyword.text, "end")
	end)

	suite:case("parseStatWhile", function(assert)
		local block = parser.parseblock("while i <= 10 do print(i); i = i + 1 end")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)

		local whileStat = block.statements[1] :: syntax.AstStatWhile
		assert.eq(whileStat.tag, "while")
		assert.eq(whileStat.whilekeyword.text, "while")
		assert.eq(whileStat.condition.tag, "binary")
		assert.eq(whileStat.dokeyword.text, "do")
		checkIsBlock(whileStat.body, assert)
		assert.eq(#whileStat.body.statements, 2)
		assert.eq(whileStat.endkeyword.text, "end")

		block = parser.parseblock("while true do break end")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)

		whileStat = block.statements[1] :: syntax.AstStatWhile
		assert.eq(whileStat.tag, "while")
		assert.eq(whileStat.whilekeyword.text, "while")
		assert.eq(whileStat.condition.tag, "boolean")
		assert.eq(whileStat.dokeyword.text, "do")
		checkIsBlock(whileStat.body, assert)
		assert.eq(#whileStat.body.statements, 1)

		local breakStat = whileStat.body.statements[1] :: syntax.AstStat
		assert.eq(breakStat.kind, "stat")
		breakStat = breakStat :: syntax.AstStatBreak
		assert.eq(breakStat.tag, "break")
		assert.eq(breakStat.text, "break")

		assert.eq(whileStat.endkeyword.text, "end")

		block = parser.parseblock("while true do continue end")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)

		whileStat = block.statements[1] :: syntax.AstStatWhile
		assert.eq(whileStat.tag, "while")
		assert.eq(whileStat.whilekeyword.text, "while")
		assert.eq(whileStat.condition.tag, "boolean")
		assert.eq(whileStat.dokeyword.text, "do")
		checkIsBlock(whileStat.body, assert)
		assert.eq(#whileStat.body.statements, 1)

		local continueStat = whileStat.body.statements[1] :: syntax.AstStat
		assert.eq(continueStat.kind, "stat")
		continueStat = continueStat :: syntax.AstStatContinue
		assert.eq(continueStat.tag, "continue")
		assert.eq(continueStat.text, "continue")

		assert.eq(whileStat.endkeyword.text, "end")
	end)

	suite:case("parseStatRepeat", function(assert)
		local block = parser.parseblock("repeat i = i + 1; print(i) until i > 5")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)

		local repeatStat = block.statements[1] :: syntax.AstStatRepeat
		assert.eq(repeatStat.tag, "repeat")
		assert.eq(repeatStat.repeatkeyword.text, "repeat")
		checkIsBlock(repeatStat.body, assert)
		assert.eq(#repeatStat.body.statements, 2)
		assert.eq(repeatStat.untilkeyword.text, "until")
		assert.eq(repeatStat.condition.tag, "binary")
	end)

	suite:case("parseStatLocal", function(assert)
		local block = parser.parseblock("local b, c = 1, 2")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)
		assert.eq(block.statements[1].kind, "stat")

		local l = block.statements[1] :: syntax.AstStatLocal
		assert.eq(l.tag, "local")
		assert.eq(l.localkeyword.text, "local")
		assert.eq(#l.variables, 2)
		assert.eq(l.variables[1].node.name.text, "b")
		assert.neq(l.variables[1].separator, nil)
		assert.eq((l.variables[1].separator :: syntax.Token<",">).text, ",")
		assert.eq(l.variables[2].node.name.text, "c")
		assert.eq(l.variables[2].separator, nil)
		assert.neq(l.equals, nil)
		assert.eq((l.equals :: syntax.Token<"=">).text, "=")
		assert.eq(#l.values, 2)
		assert.eq(l.values[1].node.tag, "number")
		assert.neq(l.values[1].separator, nil)
		assert.eq((l.values[1].separator :: syntax.Token<",">).text, ",")
		assert.eq(l.values[2].node.tag, "number")
		assert.eq(l.values[2].separator, nil)

		block = parser.parseblock("local x")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)
		assert.eq(block.statements[1].kind, "stat")

		l = block.statements[1] :: syntax.AstStatLocal
		assert.eq(l.tag, "local")
		assert.eq(l.localkeyword.text, "local")
		assert.eq(#l.variables, 1)
		assert.eq(l.variables[1].node.name.text, "x")
		assert.eq(l.variables[1].separator, nil)
		assert.eq(l.equals, nil)
		assert.eq(#l.values, 0)
	end)

	suite:case("parseStatFor", function(assert)
		local block = parser.parseblock("for i = 1, 10, 2 do print(i) end")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		local forStat = block.statements[1] :: syntax.AstStatFor
		assert.eq(forStat.tag, "for")
		assert.eq(forStat.forkeyword.text, "for")
		assert.eq(forStat.variable.name.text, "i")
		assert.eq(forStat.equals.text, "=")
		assert.eq(forStat.from.tag, "number")
		assert.eq(forStat.tocomma.text, ",")
		assert.eq(forStat.to.tag, "number")
		assert.neq(forStat.stepcomma, nil)
		assert.eq((forStat.stepcomma :: syntax.Token<",">).text, ",")
		assert.neq(forStat.step, nil)
		assert.eq(((forStat.step :: any) :: syntax.AstExpr).tag, "number")
		assert.eq(forStat.dokeyword.text, "do")
		checkIsBlock(forStat.body, assert)
		assert.eq(#forStat.body.statements, 1)
		assert.eq(forStat.endkeyword.text, "end")

		block = parser.parseblock("for j = 0, 5 do print(j) end")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		forStat = block.statements[1] :: syntax.AstStatFor
		assert.eq(forStat.tag, "for")
		assert.eq(forStat.forkeyword.text, "for")
		assert.eq(forStat.variable.name.text, "j")
		assert.eq(forStat.equals.text, "=")
		assert.eq(forStat.from.tag, "number")
		assert.eq(forStat.tocomma.text, ",")
		assert.eq(forStat.to.tag, "number")
		assert.eq(forStat.stepcomma, nil)
		assert.eq(forStat.step, nil)
		assert.eq(forStat.dokeyword.text, "do")
		checkIsBlock(forStat.body, assert)
		assert.eq(#forStat.body.statements, 1)
		assert.eq(forStat.endkeyword.text, "end")
	end)

	suite:case("parseForInLoop", function(assert)
		local block = parser.parseblock("for key, value in arr do print(key, value) end")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		local forInStat = block.statements[1] :: syntax.AstStatForIn
		assert.eq(forInStat.tag, "forin")
		assert.eq(forInStat.forkeyword.text, "for")
		assert.eq(#forInStat.variables, 2)
		assert.eq(forInStat.variables[1].node.name.text, "key")
		assert.eq(forInStat.variables[2].node.name.text, "value")
		assert.eq(forInStat.inkeyword.text, "in")
		assert.eq(#forInStat.values, 1)
		assert.eq(forInStat.values[1].node.tag, "global")
		assert.eq(forInStat.dokeyword.text, "do")
		checkIsBlock(forInStat.body, assert)
		assert.eq(#forInStat.body.statements, 1)
		assert.eq(forInStat.endkeyword.text, "end")
	end)

	suite:case("parseStatAssign", function(assert)
		local block = parser.parseblock("x = 1")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		local assign = block.statements[1] :: syntax.AstStatAssign
		assert.eq(assign.tag, "assign")
		assert.eq(#assign.variables, 1)
		assert.eq(assign.variables[1].node.tag, "global")
		assert.eq(assign.equals.text, "=")
		assert.eq(#assign.values, 1)
		assert.eq(assign.values[1].node.tag, "number")
	end)

	suite:case("parseStatCompoundAssign", function(assert)
		local block = parser.parseblock("x += 5")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		local compound = block.statements[1] :: syntax.AstStatCompoundAssign
		assert.eq(compound.tag, "compoundassign")
		assert.eq(compound.variable.tag, "global")
		assert.eq(compound.operand.text, "+=")
		assert.eq(compound.value.tag, "number")
	end)

	suite:case("parseStatFunction", function(assert)
		local block = parser.parseblock("@checked @native @deprecated function add(a, b) return a + b end")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)

		local funcStat = block.statements[1] :: syntax.AstStatFunction
		assert.eq(funcStat.tag, "function")
		assert.eq(#funcStat.attributes, 3)
		assert.eq((funcStat.attributes[1] :: syntax.AstAttribute).text, "@checked")
		assert.eq((funcStat.attributes[2] :: syntax.AstAttribute).text, "@native")
		assert.eq((funcStat.attributes[3] :: syntax.AstAttribute).text, "@deprecated")
		assert.eq(funcStat.functionkeyword.text, "function")
		assert.eq(funcStat.name.tag, "global")
		assert.eq((funcStat.name :: syntax.AstExprGlobal).name.text, "add")
		-- body parsing tested in parseExprAnonymousFunction
	end)

	suite:case("parseStatLocalFunction", function(assert)
		local block = parser.parseblock("local function multiply(x, y) return x * y end")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)

		local localFuncStat = block.statements[1] :: syntax.AstStatLocalFunction
		assert.eq(localFuncStat.tag, "localfunction")
		assert.eq(#localFuncStat.attributes, 0)
		assert.eq(localFuncStat.localkeyword.text, "local")
		assert.eq(localFuncStat.functionkeyword.text, "function")
		assert.eq(localFuncStat.name.name.text, "multiply")
	end)

	suite:case("parseStatTypeAlias", function(assert)
		local block = parser.parseblock("type Vector3 = {x: number, y: number, z: number}")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.tag, "typealias")
		assert.eq(typeAlias.export, nil)
		assert.eq(typeAlias.typetoken.text, "type")
		assert.eq(typeAlias.name.text, "Vector3")
		assert.eq(typeAlias.opengenerics, nil)
		assert.eq(typeAlias.generics, nil)
		assert.eq(typeAlias.closegenerics, nil)
		assert.eq(typeAlias.equals.text, "=")
		assert.eq(typeAlias.type.kind, "type")
		assert.eq(typeAlias.type.tag, "table")

		block = parser.parseblock("export type Point<T, U...> = {x: T, y: T, f: (U...) -> ()}")
		checkIsBlock(block, assert)
		assert.eq(#block.statements, 1)

		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.neq(typeAlias.export, nil)
		assert.eq((typeAlias.export :: syntax.Token<"export">).text, "export")
		assert.neq(typeAlias.opengenerics, nil)
		assert.eq((typeAlias.opengenerics :: syntax.Token<"<">).text, "<")
		assert.neq(typeAlias.generics, nil)
		assert.eq(#typeAlias.generics :: syntax.Punctuated<syntax.AstGenericType>, 1)
		assert.neq(typeAlias.genericpacks, nil)
		assert.eq(#typeAlias.genericpacks :: syntax.Punctuated<syntax.AstGenericTypePack>, 1)
		assert.neq(typeAlias.closegenerics, nil)
		assert.eq((typeAlias.closegenerics :: syntax.Token<">">).text, ">")
	end)

	suite:case("parseStatTypeFunction", function(assert)
		local block = parser.parseblock("type function foo() return types.number end")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		local typeFunc = block.statements[1] :: syntax.AstStatTypeFunction
		assert.eq(typeFunc.tag, "typefunction")
		assert.eq(typeFunc.export, nil)
		assert.eq(typeFunc.type.text, "type")
		assert.eq(typeFunc.functionkeyword.text, "function")
		assert.eq(typeFunc.name.text, "foo")

		block = parser.parseblock("export type function foo() return types.number end")
		assert.eq(block.tag, "block")
		assert.eq(#block.statements, 1)

		typeFunc = block.statements[1] :: syntax.AstStatTypeFunction
		assert.neq(typeFunc.export, nil)
		assert.eq((typeFunc.export :: syntax.Token<"export">).text, "export")
	end)
end)

test.suite("parse types", function(suite)
	-- AstGenericType and AstGenericTypePack are tested in parseExprAnonymousFunction
	suite:case("testTypeReference", function(assert)
		local block = parser.parseblock("type MyString = string")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "reference")

		local typeRef = typeAlias.type :: syntax.AstTypeReference
		assert.eq(typeRef.prefix, nil)
		assert.eq(typeRef.prefixpoint, nil)
		assert.eq(typeRef.name.text, "string")
		assert.eq(typeRef.openparameters, nil)
		assert.eq(typeRef.parameters, nil)
		assert.eq(typeRef.closeparameters, nil)

		block = parser.parseblock("type MyTable = MyModule.Table<number, string>")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "reference")

		typeRef = typeAlias.type :: syntax.AstTypeReference
		assert.neq(typeRef.prefix, nil)
		assert.eq((typeRef.prefix :: syntax.Token<string>).text, "MyModule")
		assert.neq(typeRef.prefixpoint, nil)
		assert.eq((typeRef.prefixpoint :: syntax.Token<".">).text, ".")
		assert.eq(typeRef.name.text, "Table")
		assert.neq(typeRef.openparameters, nil)
		assert.eq((typeRef.openparameters :: syntax.Token<"<">).text, "<")
		assert.neq(typeRef.parameters, nil)
		assert.eq(#typeRef.parameters :: syntax.Punctuated<syntax.AstType>, 2)
		assert.eq((typeRef.parameters :: syntax.Punctuated<syntax.AstType>)[1].node.tag, "reference")
		assert.eq((typeRef.parameters :: syntax.Punctuated<syntax.AstType>)[2].node.tag, "reference")
		assert.neq(typeRef.closeparameters, nil)
		assert.eq((typeRef.closeparameters :: syntax.Token<">">).text, ">")
	end)

	suite:case("testTypeSingletonBoolean", function(assert)
		local block = parser.parseblock("type TrueType = true")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "boolean")

		local singletonBool = typeAlias.type :: syntax.AstTypeSingletonBool
		assert.eq(singletonBool.text, "true")
		assert.eq(singletonBool.value, true)

		block = parser.parseblock("type FalseType = false")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "boolean")

		singletonBool = typeAlias.type :: syntax.AstTypeSingletonBool
		assert.eq(singletonBool.text, "false")
		assert.eq(singletonBool.value, false)
	end)

	suite:case("testTypeSingletonString", function(assert)
		local block = parser.parseblock("type HelloType = 'hello'")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "string")

		local singletonStr = typeAlias.type :: syntax.AstTypeSingletonString
		assert.eq(singletonStr.text, "hello")
		assert.eq(singletonStr.quotestyle, "single")

		block = parser.parseblock('type WorldType = "world"')
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "string")

		singletonStr = typeAlias.type :: syntax.AstTypeSingletonString
		assert.eq(singletonStr.text, "world")
		assert.eq(singletonStr.quotestyle, "double")
	end)

	suite:case("testTypeTypeof", function(assert)
		local block = parser.parseblock("type T = typeof(someVariable)")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "typeof")

		local typeofType = typeAlias.type :: syntax.AstTypeTypeof
		assert.eq(typeofType.typeof.text, "typeof")
		assert.eq(typeofType.openparens.text, "(")
		assert.eq(typeofType.expression.tag, "global")
		assert.eq(typeofType.closeparens.text, ")")
	end)

	suite:case("testTypeGroup", function(assert)
		local block = parser.parseblock("type T = (string)")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "group")

		local groupType = typeAlias.type :: syntax.AstTypeGroup
		assert.eq(groupType.openparens.text, "(")
		assert.eq(groupType.type.tag, "reference")
		assert.eq(groupType.closeparens.text, ")")
	end)

	suite:case("testTypeUnion", function(assert)
		local block = parser.parseblock("type T = string | number | boolean")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "union")

		local unionType = typeAlias.type :: syntax.AstTypeUnion
		assert.eq(unionType.leading, nil)
		assert.eq(#unionType.types, 3)
		assert.eq(unionType.types[1].node.tag, "reference")
		assert.eq(unionType.types[2].node.tag, "reference")
		assert.eq(unionType.types[3].node.tag, "reference")

		block = parser.parseblock("type T = | number?")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "union")

		unionType = typeAlias.type :: syntax.AstTypeUnion
		assert.neq(unionType.leading, nil)
		assert.eq((unionType.leading :: syntax.Token<"|">).text, "|")
		assert.eq(#unionType.types, 2)
		assert.eq(unionType.types[1].node.tag, "reference")
		assert.eq(unionType.types[2].node.tag, "optional")
		assert.eq((unionType.types[2].node :: syntax.AstTypeOptional).text, "?")
	end)

	suite:case("testTypeUnionWithOptionalPart", function(assert)
		local block = parser.parseblock("type T = number? | string")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "union")

		local unionType = typeAlias.type :: syntax.AstTypeUnion
		assert.eq(unionType.leading, nil)
		assert.eq(#unionType.types, 3)

		local pair1 = unionType.types[1]
		assert.eq(pair1.node.tag, "reference")
		assert.eq(pair1.separator, nil)

		local pair2 = unionType.types[2]
		assert.eq(pair2.node.tag, "optional")
		assert.neq(pair2.separator, nil)
		assert.eq((pair2.separator :: syntax.Token<"|">).text, "|")

		local pair3 = unionType.types[3]
		assert.eq(pair3.node.tag, "reference")
		assert.eq(pair3.separator, nil)
	end)

	suite:case("testTypeIntersection", function(assert)
		local block = parser.parseblock("type T = A & B & C")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "intersection")

		local intersectionType = typeAlias.type :: syntax.AstTypeIntersection
		assert.eq(intersectionType.leading, nil)
		assert.eq(#intersectionType.types, 3)
		assert.eq(intersectionType.types[1].node.tag, "reference")
		assert.eq(intersectionType.types[2].node.tag, "reference")
		assert.eq(intersectionType.types[3].node.tag, "reference")

		block = parser.parseblock("type T = & B")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "intersection")

		intersectionType = typeAlias.type :: syntax.AstTypeIntersection
		assert.neq(intersectionType.leading, nil)
		assert.eq((intersectionType.leading :: syntax.Token<"&">).text, "&")
		assert.eq(#intersectionType.types, 1)
		assert.eq(intersectionType.types[1].node.tag, "reference")
	end)

	suite:case("testTypeArray", function(assert)
		local block = parser.parseblock("type T = { number }")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "array")

		local arrayType = typeAlias.type :: syntax.AstTypeArray
		assert.eq(arrayType.openbrace.text, "{")
		assert.eq(arrayType.access, nil)
		assert.eq(arrayType.type.tag, "reference")
		assert.eq(arrayType.closebrace.text, "}")

		block = parser.parseblock("type T = { read string }")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "array")

		arrayType = typeAlias.type :: syntax.AstTypeArray
		assert.neq(arrayType.access, nil)
		assert.eq((arrayType.access :: syntax.Token<"read" | "write">).text, "read")

		block = parser.parseblock("type T = { write number }")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "array")

		arrayType = typeAlias.type :: syntax.AstTypeArray
		assert.neq(arrayType.access, nil)
		assert.eq((arrayType.access :: syntax.Token<"read" | "write">).text, "write")
	end)

	suite:case("parseTypeTable", function(assert)
		local block = parser.parseblock("type T = {}")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "table")

		local tableType = typeAlias.type :: syntax.AstTypeTable
		assert.eq(tableType.openbrace.text, "{")
		assert.eq(#tableType.entries, 0)
		assert.eq(tableType.closebrace.text, "}")

		block = parser.parseblock("type T = {[number] : string}")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "table")

		tableType = typeAlias.type :: syntax.AstTypeTable
		assert.eq(#tableType.entries, 1)
		local tableTypeItem: any = tableType.entries[1]
		assert.eq(tableTypeItem.kind, "indexer")
		assert.eq(tableTypeItem.access, nil)
		assert.eq(tableTypeItem.indexeropen.text, "[")
		assert.eq(tableTypeItem.key.tag, "reference")
		assert.eq(tableTypeItem.indexerclose.text, "]")
		assert.eq(tableTypeItem.colon.text, ":")
		assert.eq(tableTypeItem.value.tag, "reference")
		assert.eq(tableTypeItem.separator, nil)

		block = parser.parseblock("type T = {['hello'] : 'world', read ['foo'] : number; write ['bar'] : boolean}")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "table")
		tableType = typeAlias.type :: syntax.AstTypeTable
		assert.eq(#tableType.entries, 3)
		tableTypeItem = tableType.entries[1]
		assert.eq(tableTypeItem.kind, "stringproperty")
		assert.eq(tableTypeItem.access, nil)
		assert.eq(tableTypeItem.indexeropen.text, "[")
		assert.eq((tableTypeItem.key :: syntax.AstTypeSingletonString).tag, "string")
		assert.eq((tableTypeItem.key :: syntax.AstTypeSingletonString).text, "hello")
		assert.eq(tableTypeItem.indexerclose.text, "]")
		assert.eq(tableTypeItem.colon.text, ":")
		assert.eq(tableTypeItem.value.tag, "string")
		assert.neq(tableTypeItem.separator, nil)
		assert.eq((tableTypeItem.separator :: syntax.Token<"," | ";">).text, ",")

		tableTypeItem = tableType.entries[2]
		assert.eq(tableTypeItem.kind, "stringproperty")
		assert.neq(tableTypeItem.access, nil)
		assert.eq((tableTypeItem.access :: syntax.Token<"read" | "write">).text, "read")
		assert.neq(tableTypeItem.separator, nil)
		assert.eq((tableTypeItem.separator :: syntax.Token<"," | ";">).text, ";")

		tableTypeItem = tableType.entries[3]
		assert.eq(tableTypeItem.kind, "stringproperty")
		assert.neq(tableTypeItem.access, nil)
		assert.eq((tableTypeItem.access :: syntax.Token<"read" | "write">).text, "write")
		assert.eq(tableTypeItem.separator, nil)

		block = parser.parseblock("type T = { hello: 'world'; read foo: number, write bar: boolean }")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "table")
		tableType = typeAlias.type :: syntax.AstTypeTable
		assert.eq(#tableType.entries, 3)
		tableTypeItem = tableType.entries[1]
		assert.eq(tableTypeItem.kind, "property")
		assert.eq(tableTypeItem.access, nil)
		assert.eq((tableTypeItem.key :: syntax.Token).text, "hello")
		assert.eq(tableTypeItem.colon.text, ":")
		assert.eq(tableTypeItem.value.tag, "string")
		assert.neq(tableTypeItem.separator, nil)
		assert.eq((tableTypeItem.separator :: syntax.Token<"," | ";">).text, ";")

		tableTypeItem = tableType.entries[2]
		assert.eq(tableTypeItem.kind, "property")
		assert.neq(tableTypeItem.access, nil)
		assert.eq((tableTypeItem.access :: syntax.Token<"read" | "write">).text, "read")
		assert.neq(tableTypeItem.separator, nil)
		assert.eq((tableTypeItem.separator :: syntax.Token<"," | ";">).text, ",")

		tableTypeItem = tableType.entries[3]
		assert.eq(tableTypeItem.kind, "property")
		assert.neq(tableTypeItem.access, nil)
		assert.eq((tableTypeItem.access :: syntax.Token<"read" | "write">).text, "write")
		assert.eq(tableTypeItem.separator, nil)
	end)

	suite:case("parseTypeFunction", function(assert)
		local block = parser.parseblock("type T = (n : number, string) -> boolean")
		local typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "function")

		local funcType = typeAlias.type :: syntax.AstTypeFunction
		assert.eq(funcType.opengenerics, nil)
		assert.eq(funcType.generics, nil)
		assert.eq(funcType.genericpacks, nil)
		assert.eq(funcType.closegenerics, nil)
		assert.eq(funcType.openparens.text, "(")
		assert.eq(#funcType.parameters, 2)

		local param = funcType.parameters[1].node
		assert.neq(param.name, nil)
		assert.eq((param.name :: syntax.Token<string>).text, "n")
		assert.neq(param.colon, nil)
		assert.eq((param.colon :: syntax.Token<":">).text, ":")
		assert.eq(param.type.tag, "reference")

		param = funcType.parameters[2].node
		assert.eq(param.name, nil)
		assert.eq(param.colon, nil)
		assert.eq(param.type.tag, "reference")

		assert.eq(funcType.vararg, nil)
		assert.eq(funcType.closeparens.text, ")")
		assert.eq(funcType.returnarrow.text, "->")
		assert.eq(funcType.returntypes.kind, "typepack")

		block = parser.parseblock("type T = <T, U...> (item: T, ...U) -> ()")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "function")

		funcType = typeAlias.type :: syntax.AstTypeFunction
		assert.neq(funcType.opengenerics, nil)
		assert.eq((funcType.opengenerics :: syntax.Token<"<">).text, "<")
		assert.neq(funcType.generics, nil)
		assert.eq(#funcType.generics :: syntax.Punctuated<syntax.AstGenericType>, 1)
		assert.neq(funcType.genericpacks, nil)
		assert.eq(#funcType.genericpacks :: syntax.Punctuated<syntax.AstGenericTypePack>, 1)
		assert.eq((funcType.genericpacks :: syntax.Punctuated<syntax.AstGenericTypePack>)[1].node.tag, "generic")

		local genericTypePack = (funcType.genericpacks :: syntax.Punctuated<syntax.AstGenericTypePack>)[1].node
		assert.eq(genericTypePack.name.text, "U")
		assert.eq(genericTypePack.ellipsis.text, "...")

		assert.neq(funcType.closegenerics, nil)
		assert.eq((funcType.closegenerics :: syntax.Token<">">).text, ">")
		assert.neq(funcType.vararg, nil)
		assert.eq((funcType.vararg :: syntax.AstTypePack).kind, "typepack")

		block = parser.parseblock("type T = () -> ...number")
		typeAlias = block.statements[1] :: syntax.AstStatTypeAlias
		assert.eq(typeAlias.type.tag, "function")

		funcType = typeAlias.type :: syntax.AstTypeFunction
		assert.eq(funcType.returntypes.kind, "typepack")
		assert.eq(funcType.returntypes.tag, "variadic")
		local variadicType: syntax.AstTypePackVariadic = funcType.returntypes :: any
		assert.neq(variadicType.ellipsis, nil)
		assert.eq((variadicType.ellipsis :: syntax.Token<"...">).text, "...")
		assert.eq(variadicType.type.tag, "reference")
	end)
end)

test.run()
